Replace OkHttp with java Http
Taz03/instagram4j pull request #10
Opened 2023-02-11 10:43 UTC by java-coding-prodigy

Fixes #4 

One issue I am facing is the entire `CookieJar` system throughout the IG API, java http does not have a straightforward replacement to that class, and we might have to make a few utility classes to create support for the OkHttp cookie handling system

2023-02-11 11:19 UTC, Taz03 requested changes

2023-02-11 11:19 UTC, Taz03 commented on src/main/java/com/github/instagram4j/instagram4j/utils/IGUtils.java
> +    }
no don't change the formatting for now, we'll discuss on that later

2023-02-11 11:19 UTC, Taz03 commented on src/main/java/com/github/instagram4j/instagram4j/utils/IGUtils.java
> +     * @param codec  Codec to use
.

2023-02-11 11:19 UTC, Taz03 commented on src/main/java/com/github/instagram4j/instagram4j/utils/IGUtils.java
> +     * @param bytes        byte array
.

2023-02-11 11:19 UTC, Taz03 commented on src/main/java/com/github/instagram4j/instagram4j/utils/IGUtils.java
> +     *             an integer, which MOST Instagram IDs are!
.

2023-02-11 14:07 UTC, Taz03 commented
@java-coding-prodigy i'll suggest u to wait a week or two to get the tests fixed first, so it'll be easy to see if everything is ok

2023-02-11 14:08 UTC, Taz03 commented
also the cookie thing is correct, its hard to do with java's http reqs, so first come up with a solution for that and then start implementing, or remove it completely if possible

2023-02-12 04:30 UTC, java-coding-prodigy commented
> also the cookie thing is correct, its hard to do with java's http reqs, so first come up with a solution for that and then start implementing, or remove it completely if possible

So should I make my own utility class?
Or maybe find some other modern API eith good cookie handling?

2023-02-13 13:20 UTC, Taz03 commented
@java-coding-prodigy will [CookieManager](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/net/CookieManager.html) help? also i'll recommend to not work in this for a while. I might delete the project in favor of a complete rewrite. I'll ping u when things are decided

2023-02-13 17:13 UTC, java-coding-prodigy commented
I am using CookieManager only for the cookie handling, but I have to do some ugly casting from CookieHandler to manager as HttpClient returns handler but only manager has the `cookieStore()` method which is needed, shouldn't be a problem as all client builders are only using manager but still


Also for the rewrite even I think it might be necessary, migrating from okhttp3 to java http itself seems like it needs a rewrite, so keep me updated on the status.

2023-02-17 10:59 UTC, Taz03 commented
@java-coding-prodigy rewrite it is, im trying to get the basic structure down then will create a new repo

2023-02-17 10:59 UTC, closed without merging

2023-02-18 18:04 UTC, java-coding-prodigy commented
Cool, I'd like to work on some of the networking though, if possible

2023-02-18 18:16 UTC, Taz03 commented
@java-coding-prodigy r u on discord?

2023-02-18 18:20 UTC, java-coding-prodigy commented
> yes, I am `NotNull`

2023-02-18 18:20 UTC, Taz03 commented
bruh didn't knew